export const Strings ={
    pokemonList: "Pokemon List",
    home: "Home",
    myPokemonList: "My Pokemon List",
    weCanNotFindThatPage: "We can't find that page",
    returnHome: "Return Home",
    Pokemon:"Pokémon App",
    jam:"Jam",
    networkError:"network Error",
    prev:"Prev",
    next:"Next",
    name: "Name",
    flavorTextEntries:"Flavor Text Entries",
    order:"Order",
    appeal:"Appeal",
    growth:"Growth",
    names:"Names",
    condition:"condition",
    target:"Target",
    category:"Categories",
    pokemonSpecies:"pokemon Species",
    value:"values",
    contestEffects:"Contest Effects",
    effectEntries:"Effect Entries",
    contestType:"ContestType",
    maxHarvest:"Max harvest",
    smoothness:"Smoothness",
    berryFlavor:"berry_flavor",
    soilDryness:"Soil dryness",
    naturalGiftPower:"Natural gift power",
    naturalGiftPowerType:"Natural gift power type",
    firmnessesDetails:"Firmnesses Details",
    FlavorsDetails:"Flavors Details",
    nickname: "Enter the Pokemon Nickname",
    catch:"Catch",
    berries:"Berries",
    contest:"Contest",
    loading:"Loading...",
    evolution:"Evolution",
    generalDetails: "General details",
    moveAilments:"Move Ailments",
    battleStyle:"Battle Style",
    learnMethod:"LearnMethod",
    damageClass:"Damage Class",
    superContestEffects:"Super Contest Effects",
    encounterMethod:"Encounter Method",
    encounterCondition:"Encounter Condition",
    encounterConditionValue:"Encounter Condition Value",
    moves:"Moves",
    evolutionTrigger:"Evolution Trigger",
    evolutionChain:"Evolution Chain",
    encounter:"Encounter",
    viewDetail:"View Detail",
    remove:"Remove",
    processing:"Processing...",
    noDataAvailable:"No data available",
    welcomeToThePokémonApp:"Welcome to the Pokémon App!",
    startYourPokémonJourneyHere:"Start your Pokémon journey here.",
    click:"Click ",
    successful:"Successful"
}
